# Generated by Django 3.0.1 on 2021-03-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storioApp', '0002_auto_20210311_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='story_page_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
