# Generated by Django 3.0.1 on 2021-04-26 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storioApp', '0004_auto_20210320_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_back_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='story_back_color',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
