# Generated by Django 3.0.1 on 2021-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storioApp', '0005_auto_20210426_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_back_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_back_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
