# Generated by Django 3.0.1 on 2021-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storioApp', '0006_auto_20210426_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_priority', models.IntegerField()),
                ('promotion_title', models.CharField(max_length=100)),
                ('promotion_description', models.CharField(max_length=100)),
                ('promotion_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
