# Generated by Django 3.0.1 on 2021-06-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storioApp', '0007_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=200)),
                ('sentence_usage', models.CharField(max_length=200)),
                ('word_image', models.ImageField(upload_to='images/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storioApp.Story')),
            ],
        ),
    ]
